### ISSUE TITLE
ルールから必要な流れやキーワードを見つけていく

### ISSUE THREAD

**Issue by HamaguchiKazuki** [EniwaSentaiToshiking/2020-base#23]
#4 を見て必要な情報を抜き出す・調べるをしよう

**Comment by HamaguchiKazuki** [comment]
## 基本ルール (wip)
大きな課題は全部で二つ
- ライントレース
1. 機体制御 
  - PID
  - 周期ハンドラ
1. 
- 難所攻略

**Comment by ToshikiIkeda** [comment]
pid制御のライントレース、この動画わかりやすい
https://www.youtube.com/watch?v=JtaJ_ASxNP0

**Comment by HamaguchiKazuki** [comment]
こっちの[ファイル](https://github.com/EniwaSentaiToshiking/2020-base/blob/master/docs/markdown/rule_summary.md)にまとめました
