### ISSUE TITLE
astahの管理方法をどうするか決める

### ISSUE THREAD

**Issue by HamaguchiKazuki** [EniwaSentaiToshiking/2020-base#29]
## 提案1
1. astahの編集を行う時だけブランチを切る
2. 追加機能の部分だけ新しく```[機能名].asta```を作成してほかのファイルは参照だけにする
3. 編集が完了したらプルリクエストを発行して確認をとる

## 提案2
1. astahにPlantUMLの外部ライブラリを入れる
2. ブランチを切って作業をしたのち，PlantUMLに変換する
3. プルリクエストを出してPlantUMLで変換した内容を確認する

## 提案3
1. ブランチを切ってファイル名を[ファイル名]_[日付].astaに変更する
2. 作業が終わったらプルリクエストを出してマージする
3. astah-command.batを使って新・旧ファイルをマージする

## 提案4
XMLで管理する

[参考](https://astah.change-vision.com/ja/faq/faq-astah/support-teammodeling.html)

**Comment by Yuto5176** [comment]
提案２が管理しやすいのかなと思います。

**Comment by HamaguchiKazuki** [comment]
提案2はシーケンス図しか対応してなかったから提案１を改良してやりましょう
必要なファイルだけ読み込みオンリーにして参照する形で作ろう
